name:                sample-scotty
version:             0.1.0.0
github:              "mofumofuchan/sample-scotty"
license:             BSD3
author:              "OKIMOTO Yusuke"
maintainer:          "you_oki1@yahoo.co.jp"
copyright:           "2019 OKIMOTO Yusuke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mofumofuchan/sample-scotty#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sample-scotty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample-scotty
    - scotty
    - text
    - blaze-html
    - time

tests:
  sample-scotty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample-scotty
